### ISSUE TITLE
Insecure resource with Chrome and FORCE_SSL_LOGIN

### ISSUE THREAD

**Issue by pstengel** [duosecurity/duo_wordpress#11]
With `define('FORCE_SSL_LOGIN', true);` set in `wp-config.php`, duo_wordpress fails to include its Javascript library using SSL. This only seems to be a problem in Chrome (I tested Safari and Chrome), because the second factor auth in Chrome is done from the HTTPS resource, whereas Safari only seems to POST the first factor auth to the HTTPS resource, and then serves the second factor from HTTP.

To reproduce, simply install a vanilla blog, setup duo_wordpress, and add `define('FORCE_SSL_LOGIN', true);` to `wp-config.php`. Open your site in Chrome and attempt to login.

**Comment by AaronAtDuo** [comment]
Closing out this old issue.
