### ISSUE TITLE
Can't run WP CLI commands properly when DUO is active

### ISSUE THREAD

**Issue by eriktdesign** [duosecurity/duo_wordpress#23]
When logged in to my server via SSH, the DUO spits out a bunch of HTML error rubbish on the command line when running WP CLI commands.

### Reproduce:
1. Log in over SSH
2. Run a WP CLI command such as `wp plugin list`
3. Many errors are output, including PHP warnings about "cookie names must not be empty", "file_get_contents() SSL operation failed", "file_get_contents(): failed to enable crypto" etc., followed by HTML output of the WordPress login screen (with DUO iframe)

### Mitigation? 
WP CLI sets a constant called `WP_CLI`, this is the most common means of determining if a request comes from WP CLI.
So perhaps fixing this is as simple as adding the following to `duo_auth_enabled()` or `duo_role_require_mfa()`:
```php
if ( defined( 'WP_CLI' ) && WP_CLI ) {
    return false;
}
```

See WP CLI docs: https://make.wordpress.org/cli/handbook/guides/commands-cookbook/#include-in-a-plugin-or-theme

**Comment by DuoKristina** [comment]
Please create a [feature request](https://help.duo.com/s/article/5639) to let the Duo Product team know about your interest in and use cases for API/CLI access or whitelisting in the Wordpress plugin.

Thanks for trying Duo.

**Comment by AaronAtDuo** [comment]
Thank you for your interest in Duo and for submitting this Issue.  However, Duo has decided to deprecate this repository and we will not be acting on any issues or PRs on this repository going forward.  We encourage our customers to migrate their applications to the new Universal Prompt, to take advantage of improved security, user experience, and customization features.  You can find more information on migrating to the Universal Prompt at https://duo.com/docs/universal-prompt-update-guide.

You can also find more information about the deprecation at https://duosecurity.github.io/faq.html.

Thanks again for using Duo!
