### ISSUE TITLE
Can't access REST api endpoints

### ISSUE THREAD

**Issue by eriktdesign** [duosecurity/duo_wordpress#24]
We are working with a vendor to do an external connection for a WooCommerce store for product recommendations. The DUO plugin is blocking access to the REST API endpoint they are trying to use `/wp-json/wc/v3/`

It looks like this is another case where an exception needs to be added to the DUO plugin to allow external clients to connect or at least authenticate in some way.

**Comment by DuoKristina** [comment]
Please create a [feature request](https://help.duo.com/s/article/5639) to let the Duo Product team know about your interest in and use cases for API/CLI access or whitelisting in the Wordpress plugin.

Thanks for trying Duo.

**Comment by pathway27** [comment]
Yes I am also facing the same problem.

**Comment by timothyfisherdev** [comment]
I encountered an issue with this as well when using the Shippo integration with WooCommerce. I've added a comment to this PR that would fix this issue and let a specific user bypass the DUO check: https://github.com/duosecurity/duo_wordpress/pull/26#issuecomment-1125566732.

**Comment by AaronAtDuo** [comment]
Thank you for your interest in Duo and for submitting this Issue.  However, Duo has decided to deprecate this repository and we will not be acting on any issues or PRs on this repository going forward.  We encourage our customers to migrate their applications to the new Universal Prompt, to take advantage of improved security, user experience, and customization features.  You can find more information on migrating to the Universal Prompt at https://duo.com/docs/universal-prompt-update-guide.

You can also find more information about the deprecation at https://duosecurity.github.io/faq.html.

Thanks again for using Duo!
